### ISSUE TITLE
Determine trigger strategy and evalute trigger efficiency

### ISSUE THREAD

**Issue by vcepaitis** [LLPDNNX/NANOX#32]

**Comment by vcepaitis** [comment]
From bril all relevant unprescaled HLT trigger paths:

HLT_PFMET120_PFMHT120_IDTight
HLT_PFMETNoMu120_PFMHTNoMu120_IDTight

HLT_PFHT200_DiPFJetAve90_PFAlphaT0p63
HLT_PFHT250_DiPFJetAve90_PFAlphaT0p58
HLT_PFHT300_DiPFJetAve90_PFAlphaT0p54
HLT_PFHT350_DiPFJetAve90_PFAlphaT0p53
HLT_PFHT400_DiPFJetAve90_PFAlphaT0p52

HLT_PFHT300_PFMET110

HLT_PFHT900

HLT_PFJet450
HLT_PFJet500

HLT_MonoCentralPFJet80_PFMETNoMu110_PFMHTNoMu110_IDTight
HLT_MonoCentralPFJet80_PFMETNoMu120_PFMHTNoMu120_IDTight

HLT_MET200
HLT_MET250
HLT_MET300
HLT_MET600

HLT_PFMET170_HBHECleaned
HLT_PFMET300
HLT_PFMET400
HLT_PFMET500
HLT_PFMET600

**Comment by matt-komm** [comment]
thomas says that *NoMu* means that the quantity has been calculated without muons
-> so single muon data set can! be used to study the trigger strategy; muon should not be included in calculations of HT/MHT/MET then
-> single electron data set is not so optimal to study the strategy since electrons are reconstructed as jets at L1 first thus may correlated with HT/MHT

**Comment by vcepaitis** [comment]
* Postpone using the SingleElectron dataset for now.
* Plot signal efficiency as a function of MHT/MET for different benchmark scenarios.
